[phases.install]
cmds = ["npm install --prefix noc-qms-app"]

[phases.build]
cmds = ["npm run build --prefix noc-qms-app", "cp noc-qms-app/server.cjs noc-qms-app/dist/server.cjs"]

[start]
cmd = "node noc-qms-app/dist/server.cjs"
